DOMAIN_NAME: riskheatmap.security.allizom.org
ZONE_ID: Z13VQZ50081YZU
CERTIFICATE_ARN: arn:aws:acm:us-east-1:656532927350:certificate/8b9a2a12-c899-445b-b9aa-7808b6a64ab1
AUTH0_URL: auth-dev.mozilla.auth0.com
AUDIENCE: https://riskheatmap.security.allizom.org/
ENVIRONMENT: dev
REGION: us-west-2
KMSGUID: 6762fa27-618c-4c0b-83d4-ca42ffac454f
RISKS_BUCKET_NAME: infosec-risk-data-dev
RISKS_KEY_NAME: risks.json
DASHBOARD_BUCKET_NAME: infosec-observatory-dashboard-dev
DASHBOARD_KEY_NAME: index.html