DOMAIN_NAME: riskheatmap.security.allizom.org
ZONE_ID: Z13VQZ50081YZU
CERTIFICATE_ARN: arn:aws:acm:us-west-2:656532927350:certificate/5ce0db0d-88b8-4336-83e1-b8690feb4629
AUTH0_URL: auth-dev.mozilla.auth0.com
AUDIENCE: https://riskheatmap.security.allizom.org/
ENVIRONMENT: dev
REGION: us-west-2
KMSGUID: 6762fa27-618c-4c0b-83d4-ca42ffac454f
RISKS_BUCKET_NAME: infosec-risk-data-dev
RISKS_KEY_NAME: risks.json
DASHBOARD_BUCKET_NAME: infosec-observatory-dashboard-dev
DASHBOARD_KEY_NAME: index.html