DOMAIN_NAME: riskheatmap.security.mozilla.org
ZONE_ID: ZBALOKPGJTQW
CERTIFICATE_ARN: arn:aws:acm:us-west-2:371522382791:certificate/b684a800-c589-42e2-ab2a-8c5ca999d8fc
AUTH0_URL: auth.mozilla.auth0.com
AUDIENCE: https://riskheatmap.security.mozilla.org/
ENVIRONMENT: prod
REGION: us-west-2
KMSGUID: 7e581152-11be-44eb-9867-ea25afff8981
RISKS_BUCKET_NAME: infosec-risk-data
RISKS_KEY_NAME: risks.json
DASHBOARD_BUCKET_NAME: infosec-observatory-dashboard
DASHBOARD_KEY_NAME: index.html